DROP TRIGGER IF EXISTS employee_bi;
DROP SEQUENCE IF EXISTS employee_seq;
DROP TABLE IF EXISTS employee;

DROP TRIGGER IF EXISTS employee_type_bi;
DROP SEQUENCE IF EXISTS employee_type_seq;
DROP TABLE IF EXISTS employee_type;

DROP TRIGGER IF EXISTS slot_bi;
DROP SEQUENCE IF EXISTS slot_seq;
DROP TABLE IF EXISTS slot;

DROP TRIGGER IF EXISTS shelf_bi;
DROP SEQUENCE IF EXISTS shelf_seq;
DROP TABLE IF EXISTS shelf;

DROP TRIGGER IF EXISTS aisle_bi;
DROP SEQUENCE IF EXISTS aisle_seq;
DROP TABLE IF EXISTS aisle;

DROP TRIGGER IF EXISTS store_bi;
DROP SEQUENCE IF EXISTS store_seq;
DROP TABLE IF EXISTS store;
