-- Inserts para los 22 departamentos de Guatemala
insert into department ( name ) values ( 'Alta Verapaz' );
insert into department ( name ) values ( 'Baja Verapaz' );
insert into department ( name ) values ( 'Chimaltenango' );
insert into department ( name ) values ( 'Chiquimula' );
insert into department ( name ) values ( 'El Progreso' );
insert into department ( name ) values ( 'Escuintla' );
insert into department ( name ) values ( 'Guatemala' );
insert into department ( name ) values ( 'Huehuetenango' );
insert into department ( name ) values ( 'Izabal' );
insert into department ( name ) values ( 'Jalapa' );
insert into department ( name ) values ( 'Jutiapa' );
insert into department ( name ) values ( 'Petén' );
insert into department ( name ) values ( 'Quetzaltenango' );
insert into department ( name ) values ( 'Quiché' );
insert into department ( name ) values ( 'Retalhuleu' );
insert into department ( name ) values ( 'Sacatepéquez' );
insert into department ( name ) values ( 'San Marcos' );
insert into department ( name ) values ( 'Santa Rosa' );
insert into department ( name ) values ( 'Sololá' );
insert into department ( name ) values ( 'Suchitepéquez' );
insert into department ( name ) values ( 'Totonicapán' );
insert into department ( name ) values ( 'Zacapa' );