-- Insert de tiendas
INSERT INTO store (name, address, municipality_id) VALUES ('Tienda Cobán', 'Av. Central 12-34, Zona 1', 1);
INSERT INTO store (name, address, municipality_id) VALUES ('Tienda Cobán', 'Av. Sur, Zona 4', 1);
INSERT INTO store (name, address, municipality_id) VALUES ('Tienda SCV', 'San Cristóbal Verapaz, Zona 4', 3);
INSERT INTO store (name, address, municipality_id) VALUES ('Tienda Tactic', 'Calle Principal, Zona 1', 4);
INSERT INTO store (name, address, municipality_id) VALUES ('Tienda Salamá', 'Av. Principal, Zona 1', 18);
INSERT INTO store (name, address, municipality_id) VALUES ('Tienda Chimaltenango', 'Av. Principal, Zona 1', 26);
INSERT INTO store (name, address, municipality_id) VALUES ('Tienda SJC', 'San Juan Comalapa, Zona 2', 29);
INSERT INTO store (name, address, municipality_id) VALUES ('Tienda Tecpán', 'Tecpán, Zona 6', 31);
INSERT INTO store (name, address, municipality_id) VALUES ('Tienda Acatenango', 'Sobre la carretera principal', 36);
INSERT INTO store (name, address, municipality_id) VALUES ('Tienda El Tejar', 'Sobre la carretera principal', 41);
INSERT INTO store (name, address, municipality_id) VALUES ('Tienda Chiquimula', 'Calle principal, Zona 1', 42);
INSERT INTO store (name, address, municipality_id) VALUES ('Tienda Esquipulas', 'Calle principal, Zona 1', 48);
INSERT INTO store (name, address, municipality_id) VALUES ('Tienda Guastatoya', 'Av. Principal, Zona 1', 53);
INSERT INTO store (name, address, municipality_id) VALUES ('Tienda Escuintla', 'Av. Sur, Zona 4', 61);
INSERT INTO store (name, address, municipality_id) VALUES ('Tienda SLC', 'Santa Lucia Cotzumalguapa, Zona 3', 62);
INSERT INTO store (name, address, municipality_id) VALUES ('Tienda Palin', 'Centro Comercial Palin', 71);
INSERT INTO store (name, address, municipality_id) VALUES ('Tienda Guatemala', 'Zona 1', 74);
INSERT INTO store (name, address, municipality_id) VALUES ('Tienda Mixco', 'PeriRoosevelt, Zona 7', 81);
INSERT INTO store (name, address, municipality_id) VALUES ('Tienda Villa Nueva', 'Centro Comercial Santa Clara', 88);
INSERT INTO store (name, address, municipality_id) VALUES ('Tienda SMP', 'San Miguel Petapa, Zona 5', 90);
INSERT INTO store (name, address, municipality_id) VALUES ('Tienda Huehuetenango', 'Huehuetenango, Zona 1', 91);
INSERT INTO store (name, address, municipality_id) VALUES ('Tienda Soloma', 'Soloma, Zona 5', 98);
INSERT INTO store (name, address, municipality_id) VALUES ('Tienda PB', 'Puerto Barrios, Zona 1', 123);
INSERT INTO store (name, address, municipality_id) VALUES ('Tienda Livingston', 'Av. Principal, Zona 1', 124);
INSERT INTO store (name, address, municipality_id) VALUES ('Tienda Livingston', 'Av. Principal, Zona 1', 124);
INSERT INTO store (name, address, municipality_id) VALUES ('Tienda El Progreso', 'El Progreso, Zona 6', 136);
INSERT INTO store (name, address, municipality_id) VALUES ('Tienda Quetzaltenango', 'Av. Principal, Zona 1', 166);
INSERT INTO store (name, address, municipality_id) VALUES ('Tienda Coatepeque', 'Calle Principal, Zona 1', 185);
INSERT INTO store (name, address, municipality_id) VALUES ('Tienda Reu', 'Av. Norte, Zona 5', 211);
INSERT INTO store (name, address, municipality_id) VALUES ('Tienda Antigua', '6ta calle', 220);
INSERT INTO store (name, address, municipality_id) VALUES ('Tienda SLS', 'San Lucas Sacatepéquez, Las puertas', 227);
INSERT INTO store (name, address, municipality_id) VALUES ('Tienda Chiquimula', 'San Antonio, Zona 1', 273);
INSERT INTO store (name, address, municipality_id) VALUES ('Tienda Solola', 'Av. Principal, Zona 1', 280);
INSERT INTO store (name, address, municipality_id) VALUES ('Tienda Mazatenango', 'Av. Principal, Zona 1', 299);
INSERT INTO store (name, address, municipality_id) VALUES ('Tienda Totonicapan', 'Av. Principal, Zona 1', 320);
INSERT INTO store (name, address, municipality_id) VALUES ('Tienda Zacapa', 'Av. Principal, Zona 1', 328);